import { useRef, useState } from 'react';
import { api } from '../lib/api';
import { createMaterial } from '../lib/demo';
import type { JourneyData, PersonId } from '../types';

const fields: Array<[keyof JourneyData['people']['father'], string, string]> = [['birthDate', '出生日期 / 年代', '例如：1965 年'], ['birthplace', '出生地', ''], ['growthPlace', '主要成长地', ''], ['education', '教育经历', ''], ['work', '工作经历', ''], ['marriage', '婚姻经历', ''], ['wealth', '经济 / 财富经历', ''], ['majorIllness', '重大疾病', ''], ['setbacks', '重大挫折', ''], ['lifeEvents', '重要人生事件', ''], ['keyInteractions', '与我的关键互动事件', '']];
type Recognition = { lang: string; continuous: boolean; interimResults: boolean; start: () => void; onresult: ((event: any) => void) | null; onerror: (() => void) | null; onend: (() => void) | null; };
type RecognitionConstructor = new () => Recognition;

export function ParentArchive({ data, persist, toast }: { data: JourneyData; persist: (next: JourneyData) => Promise<void>; toast: (message: string) => void }) {
  const [personId, setPersonId] = useState<PersonId>('mother');
  const [text, setText] = useState(''); const [question, setQuestion] = useState(''); const [saving, setSaving] = useState(false); const [listening, setListening] = useState(false); const recognition = useRef<Recognition | null>(null);
  const person = data.people[personId]; const materials = data.materials.filter((item) => item.personId === personId);
  function update(key: keyof typeof person, value: string) { void persist({ ...data, people: { ...data.people, [personId]: { ...person, [key]: value } } }); }
  async function ask() { setQuestion(await api.interviewQuestion(personId, '父母档案自由记录', materials)); }
  async function save(source: 'write' | 'voice' = 'write') { if (!text.trim()) return; setSaving(true); try { const material = createMaterial(personId, '自由记录', text.trim(), source); await persist({ ...data, materials: [material, ...data.materials] }); setText(''); toast('原始记录已保存，内在父母画像会随新材料更新。'); } finally { setSaving(false); } }
  function voice() { const SpeechRecognition = (window as unknown as { SpeechRecognition?: RecognitionConstructor; webkitSpeechRecognition?: RecognitionConstructor }).SpeechRecognition || (window as unknown as { webkitSpeechRecognition?: RecognitionConstructor }).webkitSpeechRecognition; if (!SpeechRecognition) { toast('当前浏览器暂不支持语音转写，请使用文本输入。'); return; } const instance = new SpeechRecognition(); recognition.current = instance; instance.lang = 'zh-CN'; instance.continuous = false; instance.interimResults = false; instance.onresult = (event) => setText((current) => `${current}${current ? '\n' : ''}${Array.from(event.results).map((item: any) => item[0]?.transcript || '').join('')}`); instance.onerror = () => { setListening(false); toast('语音识别未完成，请再试一次。'); }; instance.onend = () => setListening(false); setListening(true); instance.start(); }
  return <div className="page parent-archive"><span className="eyebrow">父母档案</span><h1>从真实的故事里，<br />慢慢了解他们。</h1><div className="person-tabs">{(['mother', 'father'] as PersonId[]).map((id) => <button key={id} className={personId === id ? 'selected' : ''} onClick={() => { setPersonId(id); setText(''); setQuestion(''); }}><i className={id}>{data.people[id].avatar}</i>{id === 'mother' ? '了解妈妈' : '了解爸爸'}</button>)}</div><section className="parent-identity"><i className={personId}>{person.avatar}</i><div><b>{person.nickname}</b><span>信息可随时补充，不填不会影响自由记录。</span></div><button className="text-button" onClick={() => update('nickname', prompt('称呼', person.nickname) || person.nickname)}>修改称呼</button></section><section className="parent-basics"><h2>{personId === 'mother' ? '妈妈的基础信息' : '爸爸的基础信息'}</h2><div>{fields.map(([key, title, placeholder]) => <label key={String(key)}>{title}<input value={String(person[key] || '')} placeholder={placeholder} onChange={(event) => update(key, event.target.value)} /></label>)}</div></section><section className="parent-recorder"><header><div><span>自由记录</span><h2>写下故事、互动、说过的话或此刻浮现的感受。</h2></div><button className="text-button" onClick={() => void ask()}>让 AI 给我一个方向</button></header>{question && <div className="record-question"><span>继续记录方向</span><p>{question}</p><button onClick={() => void ask()}>换一个问题　↻</button></div>}<textarea value={text} onChange={(event) => setText(event.target.value)} placeholder={`关于${personId === 'mother' ? '妈妈' : '爸爸'}，我记得……`} /><div className="record-actions"><button type="button" className={listening ? 'voice-button listening' : 'voice-button'} onClick={voice} aria-label={listening ? '正在语音输入' : '开始语音输入'} title={listening ? '正在语音输入' : '语音输入'}>🎙</button><button className="primary" disabled={!text.trim() || saving} onClick={() => void save(listening ? 'voice' : 'write')}>{saving ? '正在保存…' : '保存原始记录'} <b>→</b></button></div></section></div>;
}
