import { useMemo, useState } from 'react';
import { api } from '../lib/api';
import type { Approval, Insight, JourneyData, PersonId } from '../types';

const labels: Record<PersonId, string> = { father: '父亲', mother: '母亲' };
const topics = ['人生背景摘要', '成长经历', '性格倾向', '核心价值观', '最看重什么', '可能最害怕什么', '爱的表达方式', '愤怒表达方式', '冲突处理方式', '对家庭的理解', '对孩子的主要期待', '对我的主要态度', '常说的话 / 语言风格', '重要人生局限', '时代与家庭环境的影响'];
export function ParentPortraits({ data, persist, toast }: { data: JourneyData; persist: (next: JourneyData) => Promise<void>; toast: (message: string) => void }) {
  const [personId, setPersonId] = useState<PersonId>('mother'); const [generating, setGenerating] = useState(false);
  const roleId = personId === 'father' ? 'innerFather' : 'innerMother'; const role = data.innerRoles.find((item) => item.id === roleId)!;
  const materials = data.materials.filter((item) => item.personId === personId); const portrait = useMemo(() => data.insights.find((item) => item.kind === 'portrait' && item.title.startsWith(`${labels[personId]} ·`)), [data.insights, personId]);
  async function generate() { if (!materials.length) { toast(`先补充一些关于${labels[personId]}的真实故事，再生成画像。`); return; } setGenerating(true); try { const output = await api.deepInsight(`请基于关于${labels[personId]}的材料，生成结构化人物画像，覆盖：${topics.join('、')}。用“根据目前信息”“可能”等措辞，不足处明确资料不足；不超过 600 字。`, materials); const next: Insight = { ...output, kind: 'portrait', title: `${labels[personId]} · 内在${labels[personId]}画像`, sourceIds: materials.map((item) => item.id), confidence: materials.length >= 6 ? '中' : '低' }; await persist({ ...data, insights: [next, ...data.insights] }); } finally { setGenerating(false); } }
  function decide(status: Approval) { if (!portrait) return; void persist({ ...data, insights: data.insights.map((item) => item.id === portrait.id ? { ...item, status } : item) }); toast('你的确认已写入后续分析。'); }
  function edit() { const name = prompt('角色称呼', role.name)?.trim(); const avatar = prompt('头像文字', role.avatar)?.trim(); if (!name || !avatar) return; void persist({ ...data, innerRoles: data.innerRoles.map((item) => item.id === role.id ? { ...item, name, avatar: avatar.slice(0, 2) } : item) }); }
  return <div className="page portraits"><span className="eyebrow">父母画像</span><h1>理解形成过程，<br />不是定义一个人。</h1><p className="page-copy">这是根据你提供的经历与感受形成的“内在父亲 / 内在母亲模型”，并不等同于现实中的父母本人。</p><div className="person-tabs">{(['mother', 'father'] as PersonId[]).map((id) => <button key={id} className={personId === id ? 'selected' : ''} onClick={() => setPersonId(id)}><i className={id}>{data.people[id].avatar}</i>内在{labels[id]}</button>)}</div><section className="portrait-profile"><i>{role.avatar}</i><div><span>内在角色</span><h2>{role.name}</h2><p>材料基础：{materials.length} 条关于{labels[personId]}的原始记录</p></div><button className="text-button" onClick={edit}>修改头像与称呼</button></section>{portrait ? <section className="portrait-result"><span>结构化画像 · 可信度 {portrait.confidence || '低'} · 待你确认</span><h2>{portrait.title}</h2><p>{portrait.body}</p><details><summary>为什么这样理解：查看 {portrait.sourceIds.length} 条依据</summary>{materials.filter((item) => portrait.sourceIds.includes(item.id)).map((item) => <p key={item.id}>· {item.text}</p>)}</details>{portrait.status === 'pending' && <div><button className="primary small" onClick={() => decide('confirmed')}>符合</button><button className="secondary" onClick={() => decide('partial')}>部分符合</button><button className="text-button" onClick={() => decide('rejected')}>不符合</button></div>}</section> : <section className="portrait-empty"><h2>{materials.length ? '可以生成一版待确认画像' : '先从真实故事开始'}</h2><p>{materials.length ? '系统会基于已有材料，清楚标记哪些是事实、哪些是可能的理解。' : `关于${labels[personId]}的资料还不足，暂不输出高确定性结论。`}</p><button className="primary" disabled={generating || !materials.length} onClick={() => void generate()}>{generating ? '正在整理画像…' : `生成内在${labels[personId]}画像`} <b>→</b></button></section>}</div>;
}
