import { useEffect, useMemo, useState } from 'react';
import { api } from '../lib/api';
import type { Approval, Insight, JourneyData, PersonId } from '../types';

const labels: Record<PersonId, string> = { father: '父亲', mother: '母亲' };
const topics = ['人生背景摘要', '成长经历', '性格倾向', '核心价值观', '最看重什么', '可能最害怕什么', '爱的表达方式', '愤怒表达方式', '冲突处理方式', '对家庭的理解', '对孩子的主要期待', '对我的主要态度', '常说的话 / 语言风格', '重要人生局限', '时代与家庭环境的影响'];
export function ParentPortraits({ data, persist, toast }: { data: JourneyData; persist: (next: JourneyData) => Promise<void>; toast: (message: string) => void }) {
  const [personId, setPersonId] = useState<PersonId>('mother'); const [generating, setGenerating] = useState(false);
  const roleId = personId === 'father' ? 'innerFather' : 'innerMother'; const role = data.innerRoles.find((item) => item.id === roleId)!;
  const materials = data.materials.filter((item) => item.personId === personId); const portrait = useMemo(() => data.insights.find((item) => item.kind === 'portrait' && item.title.startsWith(`${labels[personId]} ·`)), [data.insights, personId]);
  async function generate() { if (!materials.length || generating) return; setGenerating(true); try { const output = await api.deepInsight(`请基于关于${labels[personId]}的材料，生成结构化人物画像，覆盖：${topics.join('、')}。用“根据目前信息”“可能”等措辞，不足处明确资料不足；不超过 600 字。`, materials); const next: Insight = { ...output, kind: 'portrait', title: `${labels[personId]} · 内在${labels[personId]}画像`, sourceIds: materials.map((item) => item.id), confidence: materials.length >= 6 ? '中' : '低' }; await persist({ ...data, insights: [next, ...data.insights] }); } finally { setGenerating(false); } }
  useEffect(() => { const needsRefresh = materials.length && (!portrait || materials.some((item) => !portrait.sourceIds.includes(item.id))); if (needsRefresh) void generate(); }, [personId, data.materials]);
  function edit() { const name = prompt('角色称呼', role.name)?.trim(); const avatar = prompt('头像文字', role.avatar)?.trim(); if (!name || !avatar) return; void persist({ ...data, innerRoles: data.innerRoles.map((item) => item.id === role.id ? { ...item, name, avatar: avatar.slice(0, 2) } : item) }); }
  return <div className="page portraits"><span className="eyebrow">内在父母</span><h1>从你的经历里，<br />看见内在父母。</h1><p className="page-copy">内在父亲 / 内在母亲来自你提供的经历与感受，不等同于现实中的父母本人。新增材料后，画像会持续更新。</p><div className="person-tabs">{(['mother', 'father'] as PersonId[]).map((id) => <button key={id} className={personId === id ? 'selected' : ''} onClick={() => setPersonId(id)}><i className={id}>{data.people[id].avatar}</i>内在{labels[id]}</button>)}</div><section className="portrait-profile"><i>{role.avatar}</i><div><span>内在角色</span><h2>{role.name}</h2><p>材料基础：{materials.length} 条关于{labels[personId]}的原始记录</p></div><button className="text-button" onClick={edit}>修改头像与称呼</button></section>{portrait ? <section className="portrait-result"><span>角色画像 · 基于 {portrait.sourceIds.length} 条可追溯材料</span><h2>{portrait.title}</h2><div className="portrait-dimensions">{['人生背景与成长经历', '性格与价值观', '爱、愤怒与冲突', '家庭期待与重要局限'].map((title, index) => <article key={title}><b>{title}</b><p>{portrait.body.split(/[。！？]/).filter(Boolean).slice(index * 2, index * 2 + 2).join('。') || '资料仍在积累中。'}</p></article>)}</div><details><summary>查看形成这版画像的原始材料</summary>{materials.filter((item) => portrait.sourceIds.includes(item.id)).map((item) => <p key={item.id}>· {item.text}</p>)}</details></section> : <section className="portrait-empty"><h2>{generating ? '正在从材料中整理内在角色…' : '内在角色正在形成'}</h2><p>{materials.length ? '系统会在后台基于已有材料生成画像，并在你继续记录后持续更新。' : `关于${labels[personId]}的资料还不够，先写下一段真实经历吧。`}</p></section>}</div>;
}
