import { FormEvent, useEffect, useState } from 'react';
import { api } from './lib/api';
import { AssessmentResult, FamilyPatternTest, patternDimensions } from './components/FamilyPatternTest';
import { ParentArchive } from './components/ParentArchive';
import { ParentPortraits } from './components/ParentPortraits';
import { DynamicValidation } from './components/DynamicValidation';
import { freshJourney } from './lib/demo';
import type { Approval, FamilyPatternAssessment, Insight, JourneyData, View } from './types';
import wechatQr from './assets/wechat-qr.jpg';

const ANON_KEY = 'root-journey-anonymous-assessment';
const nav: Array<[View, string, string]> = [['home', '首页', '⌂'], ['parents', '父母档案', '◫'], ['portraits', '内在父母', '◌'], ['system', '动态校验', '✦'], ['dilemma', '时空洞察', '◷']];

export default function App() {
  const [data, setData] = useState<JourneyData>(freshJourney()); const [session, setSession] = useState(() => sessionStorage.getItem('root-journey-session') === '1'); const [view, setView] = useState<View>('home'); const [notice, setNotice] = useState(''); const [theme, setTheme] = useState<'light' | 'dark'>(() => localStorage.getItem('root-journey-theme') === 'dark' ? 'dark' : 'light'); const [gate, setGate] = useState<'assessment' | 'login'>('assessment'); const [anonymousAssessment, setAnonymousAssessment] = useState<FamilyPatternAssessment | undefined>(() => { const raw = localStorage.getItem(ANON_KEY); return raw ? JSON.parse(raw) : undefined; });
  useEffect(() => { if (!session) return; void api.load().then((saved) => { if (saved) { const base = freshJourney(); const migrated: JourneyData = { ...base, ...saved, profile: { ...base.profile, ...saved.profile, lifeStages: saved.profile?.lifeStages || [] }, people: { father: { ...base.people.father, ...saved.people?.father }, mother: { ...base.people.mother, ...saved.people?.mother } }, innerRoles: base.innerRoles.map((role) => ({ ...role, ...(saved.innerRoles || []).find((item) => item.id === role.id) })), familyAssessment: saved.familyAssessment?.answers?.length === 32 && saved.familyAssessment.scores?.length === 8 ? saved.familyAssessment : undefined }; setData(migrated); } }); }, [session]);
  useEffect(() => { if (session || anonymousAssessment) return; void api.load().then((saved) => { if (saved?.familyAssessment?.answers?.length === 32) { localStorage.setItem(ANON_KEY, JSON.stringify(saved.familyAssessment)); setAnonymousAssessment(saved.familyAssessment); } }).catch(() => undefined); }, [session, anonymousAssessment]);
  useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem('root-journey-theme', theme); }, [theme]);
  async function persist(next: JourneyData) { setData(next); await api.save(next); }
  function toast(message: string) { setNotice(message); window.setTimeout(() => setNotice(''), 2800); }
  if (!session) return gate === 'assessment' ? <AnonymousAssessment assessment={anonymousAssessment} onComplete={(assessment) => { localStorage.setItem(ANON_KEY, JSON.stringify(assessment)); setAnonymousAssessment(assessment); }} onSave={() => setGate('login')} /> : <Login assessment={anonymousAssessment} onBack={() => setGate('assessment')} onSuccess={async (phone) => { const saved = await api.load(); const next = { ...(saved || data), profile: { ...(saved || data).profile, phone }, familyAssessment: anonymousAssessment || (saved || data).familyAssessment }; localStorage.removeItem(ANON_KEY); setAnonymousAssessment(undefined); sessionStorage.setItem('root-journey-session', '1'); await persist(next); setSession(true); }} />;
  return <div className="app-shell"><aside><Brand /><nav>{nav.map(([key, title, icon]) => <button key={key} className={view === key ? 'selected' : ''} onClick={() => setView(key)}><i>{icon}</i>{title}</button>)}</nav><button className="settings" onClick={() => setView('settings')}><i>◎</i>我的</button><button className="theme-toggle" onClick={() => setTheme((current) => current === 'light' ? 'dark' : 'light')}>{theme === 'dark' ? '切换日间' : '切换夜间'}</button></aside><main>{view === 'home' && <Home data={data} setView={setView} />} {view === 'parents' && <ParentArchive data={data} persist={persist} toast={toast} />} {view === 'portraits' && <ParentPortraits data={data} persist={persist} toast={toast} />} {view === 'system' && <DynamicValidation data={data} persist={persist} toast={toast} />} {view === 'dilemma' && <SpacetimeInsight data={data} persist={persist} toast={toast} />} {view === 'assessment' && <FullAssessment data={data} persist={persist} toast={toast} />} {view === 'settings' && <BasicInfo data={data} persist={persist} onLogout={() => { if (data.familyAssessment) localStorage.setItem(ANON_KEY, JSON.stringify(data.familyAssessment)); void api.logout(); sessionStorage.removeItem('root-journey-session'); setSession(false); setGate('assessment'); }} />}</main>{notice && <div className="toast">{notice}</div>}<div className="mobile-nav">{nav.slice(0, 4).map(([key, title]) => <button key={key} className={view === key ? 'selected' : ''} onClick={() => setView(key)}>{title}</button>)}<button onClick={() => setView('settings')}>我的</button></div></div>;
}

function Brand() { return <div className="brand"><b>寻根之旅</b><span>原生家庭考古</span></div>; }
function AnonymousAssessment({ assessment, onComplete, onSave }: { assessment?: FamilyPatternAssessment; onComplete: (next: FamilyPatternAssessment) => void; onSave: () => void }) { return <div className="assessment-shell"><Brand /><FamilyPatternTest assessment={assessment} onComplete={onComplete} onUpdate={onComplete} loggedIn={false} onSave={onSave} /></div>; }
function Login({ assessment, onBack, onSuccess }: { assessment?: FamilyPatternAssessment; onBack: () => void; onSuccess: (phone: string) => void }) { const [phone, setPhone] = useState(''); const [code, setCode] = useState(''); const [sent, setSent] = useState(false); const [error, setError] = useState(''); async function submit(event: FormEvent) { event.preventDefault(); try { await api.verifyCode(phone, code); onSuccess(phone); } catch (reason) { setError(reason instanceof Error ? reason.message : '登录失败，请稍后再试。'); } } return <div className="auth-page"><section className="login"><button className="text-button" onClick={onBack}>‹ 返回测试结果</button><Brand /><h1>保存这份结果，<br />继续你的寻根之旅。</h1><p className="page-copy">登录后将自动保存本次八维测试结果，并开放父母档案、父母画像、家庭影响链与时空洞察。</p><form onSubmit={submit}><label>手机号<input value={phone} onChange={(event) => setPhone(event.target.value)} inputMode="numeric" placeholder="演示环境可任意填写" required /></label><label>验证码<div className="code-row"><input value={code} onChange={(event) => setCode(event.target.value)} inputMode="numeric" placeholder="演示验证码 123456" required /><button type="button" onClick={() => { void api.sendCode(phone); setSent(true); }}>获取验证码</button></div></label>{sent && <p className="hint">演示环境不会发送短信，请输入 123456。</p>}{error && <p className="error">{error}</p>}<button className="primary">保存结果并继续 <b>→</b></button></form><small>当前已有 {assessment?.answers.filter((item) => item !== null).length || 0} 题作答将绑定到你的账号。</small></section></div>; }
function Home({ data, setView }: { data: JourneyData; setView: (view: View) => void }) { const result = data.familyAssessment; return <div className="page home-page"><span className="eyebrow">首页</span><h1>这些家庭模式，<br />是怎么形成的？</h1>{result ? <section className="home-assessment"><AssessmentResult assessment={result} loggedIn onRestart={() => setView('assessment')} /></section> : <button className="wide-action" onClick={() => setView('assessment')}>完成原生家庭关系模式测试 <b>→</b></button>}<section className="parent-entry"><div><span>从真实故事开始</span><h2>先去了解爸爸和妈妈。</h2><p>他们如何成长、如何面对压力、如何表达爱与愤怒，都会成为理解家庭模式的具体线索。</p></div><div><button className="primary" onClick={() => setView('parents')}>了解妈妈 <b>→</b></button><button className="secondary" onClick={() => setView('parents')}>了解爸爸 <b>→</b></button></div></section><section className="home-links"><button onClick={() => setView('settings')}><b>我的基础信息</b><span>约 30 秒，帮助系统更准确理解你当下的位置。</span></button><button onClick={() => setView('system')}><b>家庭系统影响链</b><span>查看父母如何形成，又可能如何影响今天的你。</span></button><button onClick={() => setView('dilemma')}><b>时空洞察</b><span>把当下困惑放回你的真实经历里理解。</span></button></section><OneOnOne /></div>; }
function FullAssessment({ data, persist, toast }: { data: JourneyData; persist: (next: JourneyData) => Promise<void>; toast: (message: string) => void }) { const save = (assessment: FamilyPatternAssessment) => { void persist({ ...data, familyAssessment: assessment }); toast('测试结果已保存，并将用于后续探索。'); }; return <div className="page"><FamilyPatternTest assessment={data.familyAssessment} onComplete={save} onUpdate={save} loggedIn /></div>; }
function BasicInfo({ data, persist, onLogout }: { data: JourneyData; persist: (next: JourneyData) => Promise<void>; onLogout: () => void }) { const profile = data.profile; const stages = ['求学', '工作', '创业', '婚恋', '婚姻', '育儿', '人生转折', '其他']; function update(key: keyof typeof profile, value: string | string[]) { void persist({ ...data, profile: { ...profile, [key]: value } }); } return <div className="page basic-info"><span className="eyebrow">我的</span><h1>我的基础信息</h1><p className="page-copy">这些信息只会在生成家庭影响链或时空洞察时，帮助系统理解你所处的人生坐标；全部可以稍后再补。</p><section><label>称呼 / 昵称<input value={profile.name} onChange={(event) => update('name', event.target.value)} /></label><label>性别（非必填）<input value={profile.gender} onChange={(event) => update('gender', event.target.value)} /></label><label>出生年份 / 年代（非必填）<input value={profile.birthYear} onChange={(event) => update('birthYear', event.target.value)} /></label><label>出生地 / 主要成长地（非必填）<input value={profile.birthplace} onChange={(event) => update('birthplace', event.target.value)} /></label><label>兄弟姐妹情况 / 家中排行（非必填）<input value={profile.siblings} onChange={(event) => update('siblings', event.target.value)} /></label><div className="stage-picker"><span>当前人生阶段（可多选）</span>{stages.map((stage) => <button key={stage} className={profile.lifeStages.includes(stage) ? 'selected' : ''} onClick={() => update('lifeStages', profile.lifeStages.includes(stage) ? profile.lifeStages.filter((item) => item !== stage) : [...profile.lifeStages, stage])}>{stage}</button>)}</div></section><button className="logout-button" onClick={onLogout}>退出登录</button></div>; }
function ImpactChains({ data, persist, toast }: { data: JourneyData; persist: (next: JourneyData) => Promise<void>; toast: (message: string) => void }) { const [generating, setGenerating] = useState(false); const pending = data.insights.filter((item) => (item.kind === 'summary' || item.kind === 'hypothesis') && item.status === 'pending'); const active = pending[0]; const sources = data.materials.filter((item) => active?.sourceIds.includes(item.id)); async function generate() { if (!data.materials.length) { toast('先补充一些父母的真实故事，再生成动态校验。'); return; } setGenerating(true); try { const output = await api.deepInsight('基于已有父母材料，输出一条可由用户核验的、简短直接的系统洞察。不解释任务，不复述提示词，只输出洞察本身。内容可以是关于父母的一项特质、价值观、表达方式，也可以是内在父母对用户关系、情绪或选择的一项可能影响。使用“可能”保持开放，但控制在60字内。', data.materials); const next: Insight = { ...output, kind: 'hypothesis', title: '动态系统洞察', confidence: data.materials.length > 5 ? '中' : '低' }; await persist({ ...data, insights: [next, ...data.insights] }); } finally { setGenerating(false); } } function decide(status: Approval) { if (!active) return; void persist({ ...data, insights: data.insights.map((item) => item.id === active.id ? { ...item, status } : item) }); toast('已记录，正在准备下一条洞察。'); } const direct = active?.body.includes('目前材料提示：') ? active.body.split('目前材料提示：').pop() : active?.body; return <div className="page dynamic-validation"><span className="eyebrow">动态校验</span><h1>看见更真实的父母</h1><p className="page-copy">每次只校验一条。你的选择会帮助系统修正内在父母，并更准确理解它们对你的可能影响。</p>{active ? <section className="validation-card"><span>{active.kind === 'hypothesis' ? '内在父母 · 对我的可能影响' : '内在父母 · 系统洞察'}</span><p>{direct}</p><small>基于 {sources.length} 条原始材料</small><div><button className="primary small" onClick={() => decide('confirmed')}>符合</button><button className="secondary" onClick={() => decide('partial')}>部分符合</button><button className="text-button" onClick={() => decide('rejected')}>不符合</button></div></section> : <section className="empty-result"><p>当前没有等待校验的洞察。继续记录父母的故事和互动，系统会推荐下一条最值得核对的理解。</p><button className="primary" disabled={generating} onClick={() => void generate()}>{generating ? '正在形成洞察…' : '生成一条动态洞察'} <b>→</b></button></section>}</div>; }
function SpacetimeInsight({ data, persist, toast }: { data: JourneyData; persist: (next: JourneyData) => Promise<void>; toast: (message: string) => void }) { const [question, setQuestion] = useState(''); const [loading, setLoading] = useState(false); const results = data.insights.filter((item) => item.kind === 'dilemma'); async function generate() { if (!question.trim()) return; setLoading(true); try { const output = await api.deepInsight(`请按以下七部分理解用户困惑：1现在发生了什么 2可能触发什么 3过去相似经验 4家庭系统可能的影响 5为什么这样判断（列证据）6过去和现在的不同 7继续观察什么。不要把现实问题全部归因于原生家庭。困惑：${question}`, data.materials); await persist({ ...data, insights: [{ ...output, kind: 'dilemma', title: '一次时空洞察', sourceIds: output.sourceIds }, ...data.insights] }); setQuestion(''); } catch { toast('暂时无法生成洞察，请稍后再试。'); } finally { setLoading(false); } } return <div className="page"><span className="eyebrow">时空洞察</span><h1>让过去与现在，<br />在你的故事里相互照见。</h1><section className="dilemma"><label>我此刻最想弄明白的事<textarea value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="例如：为什么领导一否定我，我就特别难受？" /></label><button className="primary" disabled={loading || !question.trim()} onClick={() => void generate()}>{loading ? '正在理解…' : '开始时空洞察'} <b>→</b></button></section>{results.map((item) => <section className="spacetime-result" key={item.id}><span>{item.title} · 待确认</span><p>{item.body}</p><details><summary>为什么这样认为：查看 {item.sourceIds.length} 条原始依据</summary>{data.materials.filter((material) => item.sourceIds.includes(material.id)).map((material) => <p key={material.id}>· {material.text}</p>)}</details></section>)}</div>; }
function OneOnOne() { return <section className="one-on-one compact"><div><span>觉塑 1v1 深度沟通</span><h2>如果你希望有人陪你进一步梳理这些关系和经历。</h2><p>可以扫码联系觉塑，带着已经整理出的资料，进入更深入的工作。</p></div><img src={wechatQr} alt="觉塑微信二维码" /></section>; }
