export type PersonId = 'father' | 'mother';
export type MaterialSubject = PersonId | 'self' | 'family';
export type EvidenceType = 'fact' | 'experience' | 'interpretation' | 'hypothesis' | 'raw';
export type Approval = 'pending' | 'confirmed' | 'partial' | 'rejected';
export type View = 'home' | 'parents' | 'dilemma' | 'assessment';
export interface Person { id: PersonId; name: string; nickname: string; avatar: string; birthDate: string; birthplace: string; growthPlace: string; education: string; work: string; marriage: string; wealth: string; majorIllness: string; setbacks: string; lifeEvents: string; keyInteractions: string; }
export interface Material { id: string; personId: MaterialSubject; section: string; text: string; source: 'write' | 'interview' | 'voice'; createdAt: string; evidenceType?: EvidenceType; rawEntryId?: string; isRaw?: boolean; questionId?: string; questionText?: string; questionModule?: string; questionDimension?: string; }
export interface DilemmaModule { id: 'agency' | 'emotion' | 'relationship' | 'value'; name: string; association: number; role: '核心课题' | '伴随课题' | '辅助课题' | '深层课题'; direction: string; }
export interface EvidenceRef { sourceType: string; sourceId: string; fact: string; timeContext?: 'current' | 'past' | 'early'; }
export interface DilemmaAnalysis { coreBlock: string; patternChain: { trigger: string; interpretation: string; emotions: string[]; emotionalNeeds: string[]; automaticResponse: string; result: string; oldRule: string; }; repetition: { status: 'confirmed' | 'possible' | 'insufficient_evidence'; summary: string; adaptiveFunction?: string; evidence: EvidenceRef[]; commonPattern?: string; }; origin: { status: 'supported' | 'insufficient_evidence'; relationType: 'direct' | 'reverse' | 'compensation' | 'unknown'; summary: string; evidence: EvidenceRef[]; caveat: string; }; modules: DilemmaModule[]; newResponses: Array<{ type: 'awareness' | 'experiment' | 'reflection'; title: string; action: string }>; nextGrowth: { theme: string; why: string; openQuestions: string[] }; meta: { insightConfidence: 'low' | 'medium' | 'high'; familyLinkStrength: 'none' | 'weak' | 'moderate' | 'strong'; deepDiveRecommended: boolean; suppressCommercialCTA: boolean; }; }
export interface ParentHighValueSignals { frequentQuotes: Array<{ text: string; context: string; sourceId: string }>; shapingChains: Array<{ facts: string[]; possibleInfluence: string; sourceIds: string[] }>; implicitRules: Array<{ rule: string; confidence: 'low' | 'medium' | 'high'; sourceIds: string[] }>; positiveLegacy: Array<{ strength: string; howItShows: string; sourceIds: string[] }>; }
export interface Insight { id: string; title: string; body: string; sourceIds: string[]; status: Approval; kind: 'summary' | 'hypothesis' | 'dilemma' | 'portrait'; dilemma?: DilemmaAnalysis; confidence?: '低' | '中' | '高'; portraitSections?: Record<string, string>; portraitSummary?: string; portraitExtras?: Record<string, string>; portraitVersion?: number; materialSignature?: string; }
export interface InnerRole { id: 'innerFather' | 'innerMother'; name: string; avatar: string; trait: string; basedOn: PersonId[]; }
export interface FamilyPatternAssessment { answers: Array<number | null>; scores: number[]; completedAt: string; familyClimate?: Array<number | null>; assessmentVersion?: string; scoringVersion?: string; answerMap?: Record<string, number | null>; dimensionScores?: Record<string, number>; moduleScores?: Record<string, number>; dimensionStatuses?: Record<string, string>; contextVariances?: Record<string, 'low' | 'medium' | 'high'>; feedback?: { fit: '很符合' | '比较符合' | '一般' | '不太符合'; largestDifference?: string }; attributions?: Record<string, string>; openAnswers?: Record<string, string>; }
export interface BasicProfile { name: string; phone: string; avatar: string; motto: string; wechatQr: string; gender: string; birthYear: string; birthplace: string; siblings: string; lifeStages: string[]; }
export interface JourneyData { profile: BasicProfile; people: Record<PersonId, Person>; materials: Material[]; insights: Insight[]; innerRoles: InnerRole[]; familyAssessment?: FamilyPatternAssessment; parentHighValueSignals?: Partial<Record<PersonId, ParentHighValueSignals>>; conversionState?: { dilemmaCompleted: number; humanCtaShown?: boolean; humanCtaClicked?: boolean; }; }
